// Script pour ajouter indice_mot et indice_phrase à data.json
const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'data.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

// Indices par nom (mot court + phrase descriptive)
const hints = {
  "Tintin": { indice_mot: "reporter", indice_phrase: "Un jeune reporter belge aux aventures exotiques" },
  "Batman": { indice_mot: "chauve-souris", indice_phrase: "Le justicier masqué de Gotham City" },
  "Spider-Man": { indice_mot: "araignée", indice_phrase: "Super-héros qui grimpe aux murs à New York" },
  "Corto Maltese": { indice_mot: "marin", indice_phrase: "Aventurier marin créé par Hugo Pratt" },
  "Astérix": { indice_mot: "Gaulois", indice_phrase: "Petit Gaulois résistant à l'envahisseur romain" },
  "Lucky Luke": { indice_mot: "cow-boy", indice_phrase: "Le cow-boy qui tire plus vite que son ombre" },
  "Rorschach (Watchmen)": { indice_mot: "masque", indice_phrase: "Vigilant au masque de taches d'encre" },
  "Blacksad": { indice_mot: "détective", indice_phrase: "Détective félin dans un monde anthropomorphe" },
  "Captain America": { indice_mot: "bouclier", indice_phrase: "Super-soldat américain au bouclier" },
  "Daredevil": { indice_mot: "aveugle", indice_phrase: "Avocat aveugle justicier de Hell's Kitchen" },
  "Vito Corleone (Le Parrain)": { indice_mot: "parrain", indice_phrase: "Le chef de la famille mafieuse Corleone" },
  "Tony Montana (Scarface)": { indice_mot: "cocaïne", indice_phrase: "Traficant cubain à Miami" },
  "Neo (Matrix)": { indice_mot: "pilule", indice_phrase: "L'élu qui découvre la réalité de la matrice" },
  "Tyler Durden (Fight Club)": { indice_mot: "savon", indice_phrase: "Fondateur d'un club de combat clandestin" },
  "Hannibal Lecter": { indice_mot: "cannibale", indice_phrase: "Psychiatre cannibale au QI exceptionnel" },
  "Forrest Gump": { indice_mot: "chocolat", indice_phrase: "Simple d'esprit qui traverse l'histoire américaine" },
  "Indiana Jones": { indice_mot: "fouet", indice_phrase: "Archéologue aventurier au chapeau et au fouet" },
  "Joker (The Dark Knight)": { indice_mot: "clown", indice_phrase: "Criminel au visage de clown à Gotham" },
  "Jules Winnfield (Pulp Fiction)": { indice_mot: "bible", indice_phrase: "Tueur qui cite la Bible avant d'exécuter" },
  "Darth Vader": { indice_mot: "respirateur", indice_phrase: "Seigneur Sith à l'armure noire" },
  "Walter White (Breaking Bad)": { indice_mot: "méthamphétamine", indice_phrase: "Professeur devenu producteur de crystal" },
  "Tyrion Lannister (Game of Thrones)": { indice_mot: "nain", indice_phrase: "Nain politique le plus rusé de Westeros" },
  "Tommy Shelby (Peaky Blinders)": { indice_mot: "Birmingham", indice_phrase: "Chef de gang dans l'Angleterre des années 20" },
  "Saul Goodman (Better Call Saul)": { indice_mot: "avocat", indice_phrase: "Avocat véreux avant Breaking Bad" },
  "Omar Little (The Wire)": { indice_mot: "sifflet", indice_phrase: "Braqueur de trafiquants à Baltimore" },
  "Don Draper (Mad Men)": { indice_mot: "publicité", indice_phrase: "Directeur créatif dans les années 60" },
  "Sherlock Holmes (Sherlock)": { indice_mot: "déduction", indice_phrase: "Détective génial au manteau bleu" },
  "Michael Scofield (Prison Break)": { indice_mot: "tatouage", indice_phrase: "Ingénieur qui se fait incarcérer pour évader son frère" },
  "Rick Grimes (The Walking Dead)": { indice_mot: "shérif", indice_phrase: "Shérif survivant en monde post-apocalyptique" },
  "Eleven (Stranger Things)": { indice_mot: "télékinésie", indice_phrase: "Enfant aux pouvoirs psychiques" },
  "Socrate": { indice_mot: "maïeutique", indice_phrase: "Philosophe grec condamné à boire la ciguë" },
  "Platon": { indice_mot: "caverne", indice_phrase: "Disciple de Socrate, auteur de la théorie des Idées" },
  "Aristote": { indice_mot: "Lyceum", indice_phrase: "Philosophe grec précepteur d'Alexandre" },
  "Machiavel": { indice_mot: "Prince", indice_phrase: "Auteur du Prince, conseiller politique florentin" },
  "Nietzsche": { indice_mot: "surhomme", indice_phrase: "Philosophe de la volonté de puissance" },
  "Descartes": { indice_mot: "cogito", indice_phrase: "Philosophe du cogito ergo sum" },
  "Kant": { indice_mot: "impératif", indice_phrase: "Philosophe des Lumières de Königsberg" },
  "Hannah Arendt": { indice_mot: "banalité", indice_phrase: "Philosophe de la condition humaine" },
  "Jean-Paul Sartre": { indice_mot: "existentialisme", indice_phrase: "Philosophe de l'existentialisme et de la liberté" },
  "Michel Foucault": { indice_mot: "surveillance", indice_phrase: "Philosophe du pouvoir et des institutions" },
  "Victor Hugo": { indice_mot: "Notre-Dame", indice_phrase: "Auteur des Misérables et de Notre-Dame de Paris" },
  "Albert Camus": { indice_mot: "absurde", indice_phrase: "Auteur de L'Étranger et du Mythe de Sisyphe" },
  "George Orwell": { indice_mot: "Big Brother", indice_phrase: "Auteur de 1984 et de La Ferme des animaux" },
  "Franz Kafka": { indice_mot: "métamorphose", indice_phrase: "Auteur de La Métamorphose" },
  "Fiodor Dostoïevski": { indice_mot: "Crime", indice_phrase: "Auteur russe de Crime et Châtiment" },
  "Jules Verne": { indice_mot: "Nautilus", indice_phrase: "Auteur de Vingt mille lieues sous les mers" },
  "Ernest Hemingway": { indice_mot: "vieil homme", indice_phrase: "Auteur du Vieil Homme et la Mer" },
  "Stephen King": { indice_mot: "horreur", indice_phrase: "Maître du roman d'horreur américain" },
  "Philip K. Dick": { indice_mot: "androïdes", indice_phrase: "Auteur de science-fiction, Blade Runner" },
  "Margaret Atwood": { indice_mot: "servante", indice_phrase: "Auteure de La Servante écarlate" },
  "Al Pacino": { indice_mot: "Parrain", indice_phrase: "Acteur du Parrain et de Scarface" },
  "Robert De Niro": { indice_mot: "Taxi Driver", indice_phrase: "Acteur des Affranchis et de Taxi Driver" },
  "Leonardo DiCaprio": { indice_mot: "Titanic", indice_phrase: "Acteur de Titanic et de Revenant" },
  "Joaquin Phoenix": { indice_mot: "Joker", indice_phrase: "Acteur du Joker et de Gladiator" },
  "Brad Pitt": { indice_mot: "Fight Club", indice_phrase: "Acteur de Fight Club et d'Ocean's Eleven" },
  "Tom Hanks": { indice_mot: "Forrest", indice_phrase: "Acteur de Forrest Gump et de Cast Away" },
  "Mads Mikkelsen": { indice_mot: "Hannibal", indice_phrase: "Acteur danois de Hannibal et Casino Royale" },
  "Johnny Depp": { indice_mot: "Pirates", indice_phrase: "Acteur de Pirates des Caraïbes" },
  "Denzel Washington": { indice_mot: "Training", indice_phrase: "Acteur de Training Day et Malcolm X" },
  "Jack Nicholson": { indice_mot: "Shining", indice_phrase: "Acteur du Shining et de Vol au-dessus d'un nid de coucou" },
  "Martin Scorsese": { indice_mot: "mob", indice_phrase: "Réalisateur des Affranchis et de Taxi Driver" },
  "Christopher Nolan": { indice_mot: "Inception", indice_phrase: "Réalisateur d'Inception et de Dark Knight" },
  "Quentin Tarantino": { indice_mot: "Pulp Fiction", indice_phrase: "Réalisateur de Pulp Fiction et Kill Bill" },
  "Steven Spielberg": { indice_mot: "dinosaures", indice_phrase: "Réalisateur de Jurassic Park et E.T." },
  "Stanley Kubrick": { indice_mot: "Shining", indice_phrase: "Réalisateur de 2001 et du Shining" },
  "David Fincher": { indice_mot: "Fight Club", indice_phrase: "Réalisateur de Fight Club et Seven" },
  "Ridley Scott": { indice_mot: "Alien", indice_phrase: "Réalisateur d'Alien et de Blade Runner" },
  "Alfred Hitchcock": { indice_mot: "Psychose", indice_phrase: "Maître du suspense, auteur de Psychose" },
  "Denis Villeneuve": { indice_mot: "Dune", indice_phrase: "Réalisateur de Dune et Arrival" },
  "James Cameron": { indice_mot: "Titanic", indice_phrase: "Réalisateur de Titanic et Avatar" },
  "MrBeast": { indice_mot: "YouTube", indice_phrase: "Créateur aux défis et giveaways géants" },
  "Squeezie": { indice_mot: "streaming", indice_phrase: "Streamer et YouTuber français" },
  "Inoxtag": { indice_mot: "Minecraft", indice_phrase: "Streamer français connu pour Minecraft" },
  "Léna Situations": { indice_mot: "lifestyle", indice_phrase: "Influenceuse lifestyle française" },
  "Elon Musk": { indice_mot: "Tesla", indice_phrase: "PDG de Tesla et SpaceX" },
  "Andrew Tate": { indice_mot: "kickboxing", indice_phrase: "Influenceur controversé, ancien kickboxeur" },
  "Amixem": { indice_mot: "YouTube", indice_phrase: "YouTuber français aux vidéos variées" },
  "HugoDécrypte": { indice_mot: "actualités", indice_phrase: "YouTuber d'actualités et vulgarisation" },
  "Gary Vaynerchuk": { indice_mot: "marketing", indice_phrase: "Entrepreneur et expert en marketing" },
  "PewDiePie": { indice_mot: "YouTube", indice_phrase: "YouTuber suédois au plus d'abonnés" },
  "Mario": { indice_mot: "plombier", indice_phrase: "Plombier italien sauteur de Nintendo" },
  "Link (Zelda)": { indice_mot: "épée", indice_phrase: "Héros de la série Zelda" },
  "Lara Croft": { indice_mot: "archéologue", indice_phrase: "Archéologue aventurière de Tomb Raider" },
  "Kratos (God of War)": { indice_mot: "Sparte", indice_phrase: "Dieu de la guerre spartiate" },
  "Geralt de Riv (The Witcher)": { indice_mot: "sorcelerie", indice_phrase: "Chasseur de monstres mutant" },
  "Solid Snake (Metal Gear)": { indice_mot: "infiltration", indice_phrase: "Agent d'infiltration légendaire" },
  "Ezio Auditore (Assassin's Creed)": { indice_mot: "assassin", indice_phrase: "Assassin de la Renaissance italienne" },
  "Master Chief (Halo)": { indice_mot: "Spartan", indice_phrase: "Super-soldat Spartan de Halo" },
  "Arthur Morgan (Red Dead Redemption 2)": { indice_mot: "cow-boy", indice_phrase: "Hors-la-loi du Far West" },
  "Pac-Man": { indice_mot: "fantômes", indice_phrase: "Personnage jaune qui mange des pastilles" }
};

data.forEach(item => {
  const h = hints[item.name];
  item.indice_mot = h ? h.indice_mot : "indice";
  item.indice_phrase = h ? h.indice_phrase : `Élément de la catégorie ${item.category}`;
});

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
console.log('Indices ajoutés à', data.length, 'éléments');
